parameters:
    pictures_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $targetDirectory: '%pictures_directory%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EntityListener\TrickListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    App\EntityListener\UserListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    App\EventListener\DatabaseSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'
              priority: 500
              connection: 'default'
